### ISSUE TITLE
Prime multiplier

### ISSUE THREAD

**Issue by tansy** [jonmaiga/mx3#2]
I don't get how these numbers, I mean multipliers, are generated but noticed that the one used here is not prime number. I hava a suspition that it could be better constant and tried to generate closest possible prime number. Just adding +1 seemed to me not very optimal as it would, potentially, change too many bits, so I chose to flip every bit, one by one, and see what will happen. To my surprise I got 4 primes.

```
$ ./cmix2primes 0xbea225f9eb34556d
# orig:
x0= 0xbea225f9eb34556d
# primes:
y1= 0xbea225f9cb34556d
y2= 0xbea227f9eb34556d
y3= 0xbea625f9eb34556d
y4= 0xbeaa25f9eb34556d
```

Not all of them are created equal but they seem to be better than original. Tested them with practrand by mixing consecutive numbers, like that:
```
  mx3::C = 0xbea225f9cb34556d;
  x = 0 + mx3::C;
  while (1)
      {
      y = mx3::mix(x);
      fwrite(&y, 8, 1, stdout);
      x++;
      }
```

I don't know how to test their fitness with avalanche, therefore cannot say anything about that, except that they seem to pass smhasher. Test attached (tar.xz).

[mx3rnd_C-test.tar.gz](https://github.com/jonmaiga/mx3/files/13211206/mx3rnd_C-test.tar.gz)

**Comment by jonmaiga** [comment]
The multipliers are algorithmically generated, there is some info [here](https://jonkagstrom.com/tuning-bit-mixers/index.html) (see SFFS)  also code is available in the [Tests for Randomness](https://github.com/jonmaiga/tests-for-randomness/) suite (`-search` command line argument).

I originally did some informal tests with primes vs non-prime odd numbers but saw no difference. I think for xor shift mixers the more important properties of the multiplier is that it's odd (ensures bijective behavior) and that the number of set bits are around 50% somewhat randomly distributed (<-- this would be interesting to investigate).

To double check if primes have an edge I today ran a test on the a fast-to-evaluate 32-bit mixer `xmxmx` (16,15,14 as shift constants). I used 1000 random multipliers per 10-22 bits set (1000 multipliers with 10 bits set, 1000 with 11 bits set etc). I did this for odd-non-primes VS primes. The multipliers were selected from a TRNG stream. I stored how far each multiplier got in "Tests For Randomness" into two lists. Then employed Chi2 and Kolmogorov-Smirnov test to see if the two distributions differ. The statistics show that the two distributions are pretty much the same (ks p-value 0.99999.., chi2 0.7...), so no evidence that primes help here. However, using primes is important when for example hashing into buckets (as the modulo). Also I only examined the mixer part, but I would expect the same result for the mx3 hash.

To fully be able to evaluate your multipliers we would be good to run Pelle Evensen's excellent [RRC test](https://mostlymangling.blogspot.com/2019/12/stronger-better-morer-moremur-better.html) with PractRand or use [Tests for Randomness](https://github.com/jonmaiga/tests-for-randomness/) (has RRC built-in).

Does this sound reasonable?

**Comment by tansy** [comment]
Don't know if it sounds reasonable. I certainly think it it's reasonable. Or shall I say believe, although only to a point of test, add that's scientific approach.
I tried to test it with tfr-tool but all I managed to do was to add 64-bit search. That was easy, but making something more complicated with that is not easy for me add I don't know C++, at least not modern dialects that don't looks like C.
If I did manage to do that I would test it myself.

Also, mildly unrelated question - what is the path in tfr-tool, add it doesn't state in Readme?

**Comment by jonmaiga** [comment]
Yes, it's hard to reason about constructs with xor shift so empirical tests might have to do.

I'm going to close this issue, but thank your for the suggestion - it made me think about primes as multipliers again and do some interesting tests (I might do a proper write up on that).

I'm not sure which path you refer to in TFR? If you want you can open an issue in the TFR repo.

**Comment by tansy** [comment]
> I'm not sure which path you refer to in TFR?

`tfr-tool root-path command`

I meant "root-path".
